version: '3.8'
services:
  frontend:
    image: node:latest
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
  #mysql:
  #  image: mysql:latest
  #  container_name: mysql-container
  #  #restart: always
  #  volumes:
  #    - mysql-data:/var/lib/mysql
  #    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #  networks:
  #    - my-network
  #  environment:
  #    MYSQL_ROOT_PASSWORD: wenliang75
  #  ports:
  #    - "3396:3306"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7050:7000"
    depends_on:
      frontend:
        condition: service_started
      #mysql:
      #  condition: service_started
    #environment:
    #  DB_USER: root
    #  DB_PASSWORD: wenliang75
    #  DB_HOST: mysql-container
    #  DB_PORT: 3306
    #  DB_NAME: testdocker
    #networks:
    #  - my-network
#networks:
#  my-network:
#    driver: bridge
#volumes:
#  mysql-data:  
